server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vijender9423/configCloudServerConfigurations/
          searchPaths: configExampleService,pricingEngine
        encrypt:
          enabled: false

encrypt:
  key: i am vijender

